const socket=io(); let roomCode='', current={}, peers={};
const $=id=>document.getElementById(id); const welcome=$('welcome'), game=$('game');
function enter(kind){const name=$('name').value.trim(); if(!name)return alert('اكتب اسمك أولاً'); socket.emit(kind,kind==='create-room'?{name}:{name,code:$('code').value});}
$('create').onclick=()=>enter('create-room'); $('join').onclick=()=>enter('join-room');
socket.on('joined',({code,state})=>{roomCode=code;welcome.hidden=true;game.hidden=false;render(state)});socket.on('state',render);socket.on('announcement',x=>$('notice').textContent=x);socket.on('error-message',alert);
function render(s){current=s;$('roomCode').textContent=s.code;$('phase').textContent=({lobby:'الردهة',night:'الليل',day:'النهار',ended:'انتهت اللعبة'})[s.phase]; $('role').textContent=s.role?({mafia:'مافيا 🔪',doctor:'طبيب 🩺',detective:'محقق 🔎',citizen:'مواطن 👤'})[s.role]:'بانتظار البداية'; $('start').hidden=!(s.hostId===socket.id&&s.phase==='lobby');$('next').hidden=!(s.hostId===socket.id&&['night','day'].includes(s.phase));$('players').innerHTML='';s.players.forEach(p=>{const d=document.createElement('div');d.className='player '+(!p.alive?'dead':'');d.innerHTML=`<span>${p.name}${p.host?' 👑':''}</span>`;if(s.phase==='day'&&s.alive&&p.alive&&p.id!==socket.id){const b=document.createElement('button');b.textContent='صوّت';b.onclick=()=>socket.emit('vote',p.id);d.append(b)}$('players').append(d)});}
$('start').onclick=()=>socket.emit('start');$('next').onclick=()=>socket.emit('next-phase');
async function mic(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});$('mic').textContent='🎙️ المايك شغّال';$('mic').disabled=true;current.players.filter(p=>p.id!==socket.id).forEach(p=>connect(p.id,stream,true));socket.on('signal',async({from,data})=>{if(!peers[from])connect(from,stream,false);const pc=peers[from];if(data.type==='offer'){await pc.setRemoteDescription(data);const a=await pc.createAnswer();await pc.setLocalDescription(a);socket.emit('signal',{to:from,data:pc.localDescription})}else if(data.type==='answer')await pc.setRemoteDescription(data);else if(data.candidate)await pc.addIceCandidate(data)})}catch(e){alert('اسمح للمتصفح باستخدام المايك أولاً.')}}
function connect(id,stream,offer){const pc=peers[id]=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const a=new Audio();a.srcObject=e.streams[0];a.autoplay=true};pc.onicecandidate=e=>e.candidate&&socket.emit('signal',{to:id,data:{candidate:e.candidate}});if(offer)pc.createOffer().then(o=>pc.setLocalDescription(o)).then(()=>socket.emit('signal',{to:id,data:pc.localDescription}));}
$('mic').onclick=mic;
